/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED! */
#ifndef __FDATASYNC_BPF_SKEL_H__
#define __FDATASYNC_BPF_SKEL_H__

#include <stdlib.h>
#include <bpf/libbpf.h>

struct fdatasync_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *tbl_fdatasync;
	} maps;
	struct {
		struct bpf_program *BPF_KPROBE;
	} progs;
	struct {
		struct bpf_link *BPF_KPROBE;
	} links;
};

static void
fdatasync_bpf__destroy(struct fdatasync_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
fdatasync_bpf__create_skeleton(struct fdatasync_bpf *obj);

static inline struct fdatasync_bpf *
fdatasync_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct fdatasync_bpf *obj;

	obj = (struct fdatasync_bpf *)calloc(1, sizeof(*obj));
	if (!obj)
		return NULL;
	if (fdatasync_bpf__create_skeleton(obj))
		goto err;
	if (bpf_object__open_skeleton(obj->skeleton, opts))
		goto err;

	return obj;
err:
	fdatasync_bpf__destroy(obj);
	return NULL;
}

static inline struct fdatasync_bpf *
fdatasync_bpf__open(void)
{
	return fdatasync_bpf__open_opts(NULL);
}

static inline int
fdatasync_bpf__load(struct fdatasync_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct fdatasync_bpf *
fdatasync_bpf__open_and_load(void)
{
	struct fdatasync_bpf *obj;

	obj = fdatasync_bpf__open();
	if (!obj)
		return NULL;
	if (fdatasync_bpf__load(obj)) {
		fdatasync_bpf__destroy(obj);
		return NULL;
	}
	return obj;
}

static inline int
fdatasync_bpf__attach(struct fdatasync_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
fdatasync_bpf__detach(struct fdatasync_bpf *obj)
{
	return bpf_object__detach_skeleton(obj->skeleton);
}

static inline int
fdatasync_bpf__create_skeleton(struct fdatasync_bpf *obj)
{
	struct bpf_object_skeleton *s;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)
		return -1;
	obj->skeleton = s;

	s->sz = sizeof(*s);
	s->name = "fdatasync_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps)
		goto err;

	s->maps[0].name = "tbl_fdatasync";
	s->maps[0].map = &obj->maps.tbl_fdatasync;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs)
		goto err;

	s->progs[0].name = "BPF_KPROBE";
	s->progs[0].prog = &obj->progs.BPF_KPROBE;
	s->progs[0].link = &obj->links.BPF_KPROBE;

	s->data_sz = 2768;
	s->data = (void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xd0\x07\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0c\0\
\x0b\0\xb7\x01\0\0\0\0\0\0\x63\x1a\xfc\xff\0\0\0\0\xb7\x06\0\0\x01\0\0\0\x7b\
\x6a\xf0\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\x18\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\x15\0\x07\0\0\0\0\0\xdb\x60\0\0\
\0\0\0\0\x79\x01\0\0\0\0\0\0\xb7\x02\0\0\xfe\xff\xff\xff\x2d\x12\x0b\0\0\0\0\0\
\xb7\x01\0\0\x01\0\0\0\x7b\x10\0\0\0\0\0\0\x05\0\x08\0\0\0\0\0\xbf\xa2\0\0\0\0\
\0\0\x07\x02\0\0\xfc\xff\xff\xff\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xf0\xff\xff\
\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x04\0\0\x01\0\0\0\x85\0\0\0\x02\0\
\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x30\x01\0\0\x30\x01\
\0\0\x52\x02\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\
\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x01\0\0\0\x05\0\0\0\0\0\
\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\x19\0\0\0\0\0\0\x08\x07\
\0\0\0\x1d\0\0\0\0\0\0\x08\x08\0\0\0\x23\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\
\0\0\0\0\0\0\x02\x0a\0\0\0\x30\0\0\0\0\0\0\x08\x0b\0\0\0\x34\0\0\0\0\0\0\x08\
\x0c\0\0\0\x3a\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\
\0\x51\0\0\0\x01\0\0\0\0\0\0\0\x56\0\0\0\x01\0\0\0\x40\0\0\0\x62\0\0\0\x05\0\0\
\0\x80\0\0\0\x66\0\0\0\x09\0\0\0\xc0\0\0\0\x6c\0\0\0\0\0\0\x0e\x0d\0\0\0\x01\0\
\0\0\0\0\0\0\x01\0\0\x0d\x02\0\0\0\x7a\0\0\0\x02\0\0\0\x94\0\0\0\x01\0\0\x0c\
\x0f\0\0\0\x4c\x02\0\0\x01\0\0\x0f\0\0\0\0\x0e\0\0\0\0\0\0\0\x20\0\0\0\0\x69\
\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\
\x5f\x5f\0\x75\x33\x32\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\
\x20\x69\x6e\x74\0\x75\x36\x34\0\x5f\x5f\x75\x36\x34\0\x6c\x6f\x6e\x67\x20\x6c\
\x6f\x6e\x67\x20\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x74\x79\x70\
\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\x61\x6c\
\x75\x65\0\x74\x62\x6c\x5f\x66\x64\x61\x74\x61\x73\x79\x6e\x63\0\x6e\x65\x74\
\x64\x61\x74\x61\x5f\x73\x79\x73\x63\x61\x6c\x6c\x5f\x66\x64\x61\x74\x61\x73\
\x79\x6e\x63\0\x42\x50\x46\x5f\x4b\x50\x52\x4f\x42\x45\0\x6b\x70\x72\x6f\x62\
\x65\x2f\x5f\x5f\x73\x79\x73\x5f\x66\x64\x61\x74\x61\x73\x79\x6e\x63\0\x2f\x68\
\x6f\x6d\x65\x2f\x74\x68\x69\x61\x67\x6f\x2f\x4e\x65\x74\x64\x61\x74\x61\x2f\
\x6b\x65\x72\x6e\x65\x6c\x2d\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\x2f\x62\x74\
\x66\x2f\x66\x64\x61\x74\x61\x73\x79\x6e\x63\x2e\x62\x70\x66\x2e\x63\0\x69\x6e\
\x74\x20\x42\x50\x46\x5f\x4b\x50\x52\x4f\x42\x45\x28\x6e\x65\x74\x64\x61\x74\
\x61\x5f\x73\x79\x73\x63\x61\x6c\x6c\x5f\x66\x64\x61\x74\x61\x73\x79\x6e\x63\
\x29\0\x2f\x68\x6f\x6d\x65\x2f\x74\x68\x69\x61\x67\x6f\x2f\x4e\x65\x74\x64\x61\
\x74\x61\x2f\x6b\x65\x72\x6e\x65\x6c\x2d\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\
\x2f\x62\x74\x66\x2f\x6b\x65\x72\x6e\x65\x6c\x2f\x6c\x69\x62\x6e\x65\x74\x64\
\x61\x74\x61\x5f\x65\x62\x70\x66\x2e\x68\0\x20\x20\x20\x20\x72\x65\x73\x20\x3d\
\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\x65\x6c\x65\
\x6d\x28\x74\x62\x6c\x2c\x20\x26\x6b\x65\x79\x29\x3b\0\x20\x20\x20\x20\x69\x66\
\x20\x28\x72\x65\x73\x29\0\x20\x20\x20\x20\x5f\x5f\x73\x79\x6e\x63\x5f\x66\x65\
\x74\x63\x68\x5f\x61\x6e\x64\x5f\x61\x64\x64\x28\x72\x65\x73\x2c\x20\x76\x61\
\x6c\x75\x65\x29\x3b\0\x20\x20\x20\x20\x69\x66\x20\x28\x20\x28\x30\x78\x46\x46\
\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x46\x20\x2d\x20\x2a\x72\
\x65\x73\x29\x20\x3c\x3d\x20\x76\x61\x6c\x75\x65\x29\x20\x7b\0\x20\x20\x20\x20\
\x20\x20\x20\x20\x2a\x72\x65\x73\x20\x3d\x20\x76\x61\x6c\x75\x65\x3b\0\x20\x20\
\x20\x20\x20\x20\x20\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x75\x70\x64\x61\x74\
\x65\x5f\x65\x6c\x65\x6d\x28\x74\x62\x6c\x2c\x20\x26\x6b\x65\x79\x2c\x20\x26\
\x76\x61\x6c\x75\x65\x2c\x20\x42\x50\x46\x5f\x4e\x4f\x45\x58\x49\x53\x54\x29\
\x3b\0\x20\x20\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x30\x3b\0\x2e\x6d\x61\x70\
\x73\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\xbc\0\0\0\xd0\0\0\0\
\0\0\0\0\x08\0\0\0\x9f\0\0\0\x01\0\0\0\0\0\0\0\x10\0\0\0\x10\0\0\0\x9f\0\0\0\
\x0b\0\0\0\0\0\0\0\xb6\0\0\0\xf0\0\0\0\0\x8c\0\0\x28\0\0\0\xb6\0\0\0\0\0\0\0\0\
\0\0\0\x30\0\0\0\x1a\x01\0\0\x5d\x01\0\0\x0b\x78\0\0\x48\0\0\0\x1a\x01\0\0\x87\
\x01\0\0\x09\x7c\0\0\x50\0\0\0\x1a\x01\0\0\x94\x01\0\0\x05\x54\0\0\x58\0\0\0\
\x1a\x01\0\0\xba\x01\0\0\x20\x58\0\0\x68\0\0\0\x1a\x01\0\0\xba\x01\0\0\x0a\x58\
\0\0\x78\0\0\0\x1a\x01\0\0\xeb\x01\0\0\x0e\x5c\0\0\x90\0\0\0\x1a\x01\0\0\0\0\0\
\0\0\0\0\0\xa8\0\0\0\x1a\x01\0\0\x01\x02\0\0\x09\x88\0\0\xc8\0\0\0\xb6\0\0\0\
\x3e\x02\0\0\x05\x9c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x7c\0\0\0\0\0\x02\0\x88\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x75\0\0\0\0\0\x02\
\0\xc8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x6a\0\0\0\x12\0\x02\0\0\0\0\0\0\0\0\0\xd8\0\0\0\0\0\0\0\x43\0\0\0\
\x11\0\x03\0\0\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x30\0\0\0\0\0\0\0\x01\0\0\0\x05\
\0\0\0\xa8\0\0\0\0\0\0\0\x01\0\0\0\x05\0\0\0\x40\x01\0\0\0\0\0\0\0\0\0\0\x05\0\
\0\0\x2c\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\
\x50\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\x60\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\x70\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\x90\0\0\0\0\
\0\0\0\0\0\0\0\x03\0\0\0\xa0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\xb0\0\0\0\0\0\0\0\
\0\0\0\0\x03\0\0\0\xc0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\xd0\0\0\0\0\0\0\0\0\0\0\
\0\x03\0\0\0\xe0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\x28\x29\0\x2e\x74\x65\x78\x74\
\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x2e\x6d\x61\x70\x73\0\x2e\
\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x2e\x72\x65\x6c\x6b\x70\x72\
\x6f\x62\x65\x2f\x5f\x5f\x73\x79\x73\x5f\x66\x64\x61\x74\x61\x73\x79\x6e\x63\0\
\x74\x62\x6c\x5f\x66\x64\x61\x74\x61\x73\x79\x6e\x63\0\x2e\x73\x74\x72\x74\x61\
\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x42\x50\
\x46\x5f\x4b\x50\x52\x4f\x42\x45\0\x4c\x42\x42\x30\x5f\x34\0\x4c\x42\x42\x30\
\x5f\x33\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\
\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2c\0\0\0\x01\0\0\0\x06\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\xd8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x18\x01\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x65\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\
\x01\0\0\0\0\0\0\x9a\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd2\x04\0\0\0\0\0\
\0\xf0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x59\0\0\
\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\x05\0\0\0\0\0\0\x90\0\0\0\0\0\
\0\0\x0b\0\0\0\x04\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x28\0\0\0\x09\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x58\x06\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x06\0\
\0\0\x02\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x61\0\0\0\x09\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x78\x06\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x06\0\0\0\x04\0\
\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x07\0\0\0\x09\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x88\x06\0\0\0\0\0\0\xc0\0\0\0\0\0\0\0\x06\0\0\0\x05\0\0\0\x08\0\
\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x1a\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\
\0\0\0\0\0\0\x48\x07\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x51\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4a\
\x07\0\0\0\0\0\0\x83\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0";

	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return -1;
}

#endif /* __FDATASYNC_BPF_SKEL_H__ */
